import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header_Desktop";
import BreadFrame from "./components/Breadcrumbs";
import LogoSearch from "./components/LogoSearch";
import FilterFrame from "./components/FilterFrame";
import { Providers } from "./components/providers";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <BreadFrame />
          <LogoSearch />
          <FilterFrame />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
